[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/buoy"
  to = "/.netlify/functions/buoy"
  status = 200

[[redirects]]
  from = "/api/surfcheck"
  to = "/.netlify/functions/surfcheck"
  status = 200

[[redirects]]
  from = "/api/tides"
  to = "/.netlify/functions/tides"
  status = 200
